import type { Feature, Stat, BusRoute, Faculty, Event, Club, Question, Confession, ToolkitItem, CampusLocation } from '@/types';

// ─── Navigation ──────────────────────────────────────────────────────────────
export const NAV_LINKS = [
  { label: 'Home', path: '/' },
  { label: 'Notes', path: '/notes' },
  { label: 'AI Assistant', path: '/ai-assistant' },
  { label: 'Campus', path: '/campus' },
  { label: 'Clubs', path: '/events' },
  { label: 'Community', path: '/community' },
];

// ─── Stats ────────────────────────────────────────────────────────────────────
export const STATS: Stat[] = [
  { value: 20, suffix: '+', label: 'Sports', icon: 'Trophy' },
  { value: 100, suffix: '+', label: 'Faculty', icon: 'Users' },
  { value: 18, suffix: '', label: 'Clubs', icon: 'Star' },
  { value: 24, suffix: '/7', label: 'AI Assistant', icon: 'Bot' },
  { value: 5000, suffix: '+', label: 'Students', icon: 'GraduationCap' },
];

// ─── Features ────────────────────────────────────────────────────────────────
export const FEATURES: Feature[] = [
  {
    id: 'notes',
    icon: 'BookOpen',
    title: 'Notes & PYQs',
    description: 'Access semester-wise notes, previous year question papers, and study materials instantly.',
    path: '/notes',
    color: '#F97316',
    bgColor: '#FFF7ED',
  },
  {
    id: 'ai',
    icon: 'Bot',
    title: 'AI Fresher Assistant',
    description: 'Get instant answers about campus life, academics, rules, and everything RIT – powered by Gemini AI.',
    path: '/ai-assistant',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
  },
  {
    id: 'map',
    icon: 'Map',
    title: 'Campus Map',
    description: 'Explore RIT campus interactively – find departments, labs, library, canteen, and facilities.',
    path: '/campus?tab=map',
    color: '#10B981',
    bgColor: '#ECFDF5',
  },
  {
    id: 'bus',
    icon: 'Bus',
    title: 'Bus Routes',
    description: 'View all campus bus routes, timings, and pickup locations at a glance.',
    path: '/campus?tab=bus',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
  },
  {
    id: 'faculty',
    icon: 'UserCheck',
    title: 'Faculty Directory',
    description: 'Find faculty contact details, department, designation, and office hours.',
    path: '/campus?tab=faculty',
    color: '#EC4899',
    bgColor: '#FDF2F8',
  },
  {
    id: 'qa',
    icon: 'MessageCircle',
    title: 'Freshers Q&A',
    description: 'Ask questions, get answers from seniors, and join the freshers community discussion.',
    path: '/community',
    color: '#F59E0B',
    bgColor: '#FFFBEB',
  },
  {
    id: 'events',
    icon: 'Users',
    title: 'Student Clubs',
    description: 'Discover official RIT student clubs, technology domains, leadership, and contacts.',
    path: '/events',
    color: '#EF4444',
    bgColor: '#FEF2F2',
  },
  {
    id: 'toolkit',
    icon: 'Wrench',
    title: 'Student Toolkit',
    description: 'Download timetables, academic calendar, syllabus, forms, and ERP guides.',
    path: '/notes',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
  },
  {
    id: 'confession',
    icon: 'Heart',
    title: 'Anonymous Confession',
    description: 'Share your thoughts, feelings, and confessions anonymously with the RIT community.',
    path: '/community',
    color: '#F97316',
    bgColor: '#FFF7ED',
  },
];

// ─── Bus Routes ──────────────────────────────────────────────────────────────
export const BUS_ROUTES: BusRoute[] = [
  {
    id: '1',
    number: 'RIT-01',
    name: 'Chennai Central Route',
    from: 'Chennai Central',
    to: 'RIT Campus',
    departureTime: '07:00 AM',
    arrivalTime: '08:30 AM',
    color: '#F97316',
    stops: [
      { name: 'Chennai Central', time: '07:00 AM' },
      { name: 'Koyambedu', time: '07:30 AM' },
      { name: 'Porur', time: '08:00 AM' },
      { name: 'RIT Campus', time: '08:30 AM' },
    ],
  },
  {
    id: '2',
    number: 'RIT-02',
    name: 'Tambaram Express',
    from: 'Tambaram',
    to: 'RIT Campus',
    departureTime: '07:15 AM',
    arrivalTime: '08:45 AM',
    color: '#3B82F6',
    stops: [
      { name: 'Tambaram', time: '07:15 AM' },
      { name: 'Chrompet', time: '07:35 AM' },
      { name: 'Pallavaram', time: '07:55 AM' },
      { name: 'RIT Campus', time: '08:45 AM' },
    ],
  },
  {
    id: '3',
    number: 'RIT-03',
    name: 'Anna Nagar Route',
    from: 'Anna Nagar',
    to: 'RIT Campus',
    departureTime: '07:20 AM',
    arrivalTime: '08:50 AM',
    color: '#10B981',
    stops: [
      { name: 'Anna Nagar', time: '07:20 AM' },
      { name: 'Vadapalani', time: '07:45 AM' },
      { name: 'Valasaravakkam', time: '08:10 AM' },
      { name: 'RIT Campus', time: '08:50 AM' },
    ],
  },
  {
    id: '4',
    number: 'RIT-04',
    name: 'OMR Tech Route',
    from: 'Sholinganallur',
    to: 'RIT Campus',
    departureTime: '07:00 AM',
    arrivalTime: '08:30 AM',
    color: '#8B5CF6',
    stops: [
      { name: 'Sholinganallur', time: '07:00 AM' },
      { name: 'Perungudi', time: '07:20 AM' },
      { name: 'Medavakkam', time: '07:45 AM' },
      { name: 'RIT Campus', time: '08:30 AM' },
    ],
  },
];

// ─── Faculty ─────────────────────────────────────────────────────────────────
export const FACULTY_DATA: Faculty[] = [
  {
    id: '1',
    name: 'Dr. S. Ramesh Kumar',
    designation: 'Professor & HOD',
    department: 'Computer Science & Engineering',
    office: 'CSE Block, Room 301',
    specialization: 'Machine Learning, Artificial Intelligence',
    email: 'ramesh@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '18 Years',
    subjectsHandling: 'Machine Learning, Artificial Intelligence, Data Mining',
    researchAreas: 'AI, Deep Learning, Computer Vision',
    officeHours: 'Mon–Fri, 10:00 AM–12:00 PM',
    phone: '+91 98765 43001',
  },
  {
    id: '2',
    name: 'Dr. S. Priya',
    designation: 'Assistant Professor',
    department: 'Computer Science & Engineering',
    office: 'CSE Block, Room 205',
    specialization: 'Cyber Security, Computer Networks',
    email: 'priya@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '8 Years',
    subjectsHandling: 'Network Security, Computer Networks, Ethical Hacking',
    researchAreas: 'Cyber Security, IoT Security',
    officeHours: 'Mon–Fri, 2:00 PM–4:00 PM',
    phone: '+91 98765 43002',
  },
  {
    id: '3',
    name: 'Dr. K. Aravind',
    designation: 'Associate Professor',
    department: 'Computer Science & Engineering',
    office: 'CSE Block, Room 212',
    specialization: 'Cloud Computing, Distributed Systems',
    email: 'aravind@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '11 Years',
    subjectsHandling: 'Cloud Computing, Distributed Systems, Operating Systems',
    researchAreas: 'Cloud Infrastructure, Edge Computing',
    officeHours: 'Mon–Fri, 9:30 AM–11:30 AM',
    phone: '+91 98765 43003',
  },

  {
    id: '6',
    name: 'Dr. P. Mahalakshmi',
    designation: 'Associate Professor',
    department: 'Electronics & Communication Engineering',
    office: 'ECE Block, Room 205',
    specialization: 'VLSI Design, Embedded Systems',
    email: 'mahalakshmi@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '13 Years',
    subjectsHandling: 'VLSI Design, Embedded Systems',
    researchAreas: 'Chip Design, IoT Devices',
    officeHours: 'Mon–Fri, 10:00 AM–12:00 PM',
    phone: '+91 98765 43006',
  },
  {
    id: '7',
    name: 'Dr. V. Prakash',
    designation: 'Professor',
    department: 'Electronics & Communication Engineering',
    office: 'ECE Block, Room 310',
    specialization: 'Digital Signal Processing, IoT',
    email: 'prakash@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '17 Years',
    subjectsHandling: 'DSP, IoT, Microprocessors',
    researchAreas: 'Wireless Systems, Signal Processing',
    officeHours: 'Mon–Fri, 2:00 PM–4:00 PM',
    phone: '+91 98765 43007',
  },
  {
    id: '8',
    name: 'Dr. A. Deepika',
    designation: 'Assistant Professor',
    department: 'Electronics & Communication Engineering',
    office: 'ECE Block, Room 214',
    specialization: 'Wireless Communication, 5G Networks',
    email: 'deepika@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '6 Years',
    subjectsHandling: 'Wireless Networks, Mobile Communication',
    researchAreas: '5G, IoT Networks',
    officeHours: 'Mon–Fri, 9:00 AM–11:00 AM',
    phone: '+91 98765 43008',
  },
  {
    id: '9',
    name: 'Prof. R. Vijayakumar',
    designation: 'Assistant Professor',
    department: 'Mechanical Engineering',
    office: 'MECH Block, Room 102',
    specialization: 'CAD/CAM, Robotics',
    email: 'vijayakumar@rit.edu',
    qualification: 'B.E., M.E.',
    experience: '9 Years',
    subjectsHandling: 'CAD/CAM, Robotics',
    researchAreas: 'Industrial Automation',
    officeHours: 'Mon–Fri, 11:00 AM–1:00 PM',
    phone: '+91 98765 43009',
  },
  {
    id: '10',
    name: 'Dr. S. Manikandan',
    designation: 'Associate Professor',
    department: 'Mechanical Engineering',
    office: 'MECH Block, Room 118',
    specialization: 'Thermal Engineering, Manufacturing',
    email: 'manikandan@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '12 Years',
    subjectsHandling: 'Manufacturing Technology, Thermal Engineering',
    researchAreas: 'Renewable Energy, Thermal Systems',
    officeHours: 'Mon–Fri, 1:00 PM–3:00 PM',
    phone: '+91 98765 43010',
  },
  {
    id: '11',
    name: 'Prof. M. Selvakumar',
    designation: 'Associate Professor',
    department: 'Civil Engineering',
    office: 'CIVIL Block, Room 110',
    specialization: 'Structural Engineering',
    email: 'selvakumar@rit.edu',
    qualification: 'B.E., M.E.',
    experience: '14 Years',
    subjectsHandling: 'Structural Analysis, RCC Design',
    researchAreas: 'Earthquake Resistant Structures',
    officeHours: 'Mon–Fri, 10:00 AM–12:00 PM',
    phone: '+91 98765 43011',
  },
  {
    id: '12',
    name: 'Dr. J. Revathi',
    designation: 'Assistant Professor',
    department: 'Civil Engineering',
    office: 'CIVIL Block, Room 123',
    specialization: 'Environmental Engineering, Surveying',
    email: 'revathi@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '8 Years',
    subjectsHandling: 'Surveying, Environmental Engineering',
    researchAreas: 'Water Resource Management',
    officeHours: 'Mon–Fri, 2:00 PM–4:00 PM',
    phone: '+91 98765 43012',
  },
  {
    id: '13',
    name: 'Dr. N. Hariharan',
    designation: 'Professor & HOD',
    department: 'Artificial Intelligence & Data Science',
    office: 'AIDS Block, Room 501',
    specialization: 'Deep Learning, Data Mining',
    email: 'hariharan@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '19 Years',
    subjectsHandling: 'Deep Learning, Data Mining, AI',
    researchAreas: 'Artificial Intelligence, Predictive Analytics',
    officeHours: 'Mon–Fri, 9:30 AM–11:30 AM',
    phone: '+91 98765 43013',
  },
  {
    id: '14',
    name: 'Dr. P. Divya',
    designation: 'Assistant Professor',
    department: 'Artificial Intelligence & Data Science',
    office: 'AIDS Block, Room 505',
    specialization: 'Natural Language Processing, Computer Vision',
    email: 'divya@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '7 Years',
    subjectsHandling: 'NLP, Computer Vision',
    researchAreas: 'Generative AI, Image Processing',
    officeHours: 'Mon–Fri, 1:00 PM–3:00 PM',
    phone: '+91 98765 43014',
  },
  {
    id: '15',
    name: 'Dr. L. Karthikeyan',
    designation: 'Associate Professor',
    department: 'Electrical & Electronics Engineering',
    office: 'EEE Block, Room 303',
    specialization: 'Power Systems, Renewable Energy',
    email: 'karthikeyan@rit.edu',
    qualification: 'B.E., M.E., Ph.D.',
    experience: '15 Years',
    subjectsHandling: 'Power Systems, Electrical Machines',
    researchAreas: 'Smart Grid, Solar Energy',
    officeHours: 'Mon–Fri, 10:00 AM–12:00 PM',
    phone: '+91 98765 43015',
  },
  {
    id: '16',
    name: 'Dr. M. Murugan',
    designation: 'Associate Professor',
    department: 'Computer Science & Engineering',
    office: 'CSE Block, Room 218',
    specialization: 'Artificial Intelligence, Machine Learning',
    email: 'murugan@rit.edu',
    qualification: 'B.E. (CSE), M.E. (Computer Science & Engineering), Ph.D. (Artificial Intelligence)',
    experience: '13 Years',
    subjectsHandling: 'Artificial Intelligence, Machine Learning, Python Programming, Data Mining',
    researchAreas: 'Deep Learning, Computer Vision, Natural Language Processing, Explainable AI',
    officeHours: 'Mon–Fri, 10:00 AM–12:00 PM',
    phone: '+91 98765 43125',
  },
  {
    id: '17',
    name: 'Dr. R. Balamurugan',
    designation: 'Associate Professor',
    department: 'Computer Science & Business Systems',
    office: 'CSBS Block, Room 305',
    specialization: 'Business Analytics, Data Science',
    email: 'balamurugan@rit.edu',
    qualification: 'B.E. (CSE), M.B.A., M.E. (Software Engineering), Ph.D. (Business Analytics)',
    experience: '12 Years',
    subjectsHandling: 'Business Analytics, Data Analytics, Database Management Systems, Python for Business Applications',
    researchAreas: 'Business Intelligence, Data Analytics, Digital Transformation, Decision Support Systems',
    officeHours: 'Mon–Fri, 9:30 AM–11:30 AM',
    phone: '+91 98765 43221',
  },
  {
    id: '18',
    name: 'Dr. K. Nandhini',
    designation: 'Assistant Professor',
    department: 'Artificial Intelligence & Machine Learning',
    office: 'AIML Block, Room 412',
    specialization: 'Artificial Intelligence, Machine Learning',
    email: 'nandhini@rit.edu',
    qualification: 'B.E. (CSE), M.Tech. (Artificial Intelligence), Ph.D. (Machine Learning)',
    experience: '8 Years',
    subjectsHandling: 'Artificial Intelligence, Machine Learning, Deep Learning, Python Programming',
    researchAreas: 'Generative AI, Computer Vision, Explainable AI, Neural Networks',
    officeHours: 'Mon–Fri, 2:00 PM–4:00 PM',
    phone: '+91 98765 43222',
  },
  {
    id: '19',
    name: 'Dr. S. Rajeshwari',
    designation: 'Professor',
    department: 'Computer Science & Business Systems',
    office: 'CSBS Block, Room 302',
    specialization: 'Business Intelligence, Enterprise Systems',
    email: 'rajeshwari@rit.edu',
    qualification: 'B.E. (CSE), M.E. (Computer Science), Ph.D. (Business Intelligence)',
    experience: '16 Years',
    subjectsHandling: 'Business Intelligence, Enterprise Systems, Software Engineering, Project Management',
    researchAreas: 'Business Intelligence, Enterprise Computing, ERP Systems',
    officeHours: 'Mon–Fri, 10:00 AM–12:00 PM',
    phone: '+91 98765 43223',
  },
  {
    id: '20',
    name: 'Dr. V. Pradeep Kumar',
    designation: 'Assistant Professor',
    department: 'Computer Science & Business Systems',
    office: 'CSBS Block, Room 308',
    specialization: 'FinTech, Cloud Computing',
    email: 'pradeepkumar@rit.edu',
    qualification: 'B.E. (IT), M.Tech. (Cloud Computing), Ph.D. (Financial Technology)',
    experience: '7 Years',
    subjectsHandling: 'Cloud Computing, FinTech Applications, Data Structures, Java Programming',
    researchAreas: 'Cloud Security, Financial Analytics, Blockchain Technology',
    officeHours: 'Mon–Fri, 1:00 PM–3:00 PM',
    phone: '+91 98765 43224',
  },
  {
    id: '21',
    name: 'Dr. P. Harini',
    designation: 'Associate Professor',
    department: 'Artificial Intelligence & Machine Learning',
    office: 'AIML Block, Room 408',
    specialization: 'Deep Learning, Computer Vision',
    email: 'harini@rit.edu',
    qualification: 'B.E. (CSE), M.Tech. (Artificial Intelligence), Ph.D. (Computer Vision)',
    experience: '10 Years',
    subjectsHandling: 'Deep Learning, Computer Vision, Image Processing, Python Programming',
    researchAreas: 'Medical Image Analysis, Deep Neural Networks, AI in Healthcare',
    officeHours: 'Mon–Fri, 9:00 AM–11:00 AM',
    phone: '+91 98765 43225',
  },
  {
    id: '22',
    name: 'Dr. A. Vignesh',
    designation: 'Assistant Professor',
    department: 'Artificial Intelligence & Machine Learning',
    office: 'AIML Block, Room 415',
    specialization: 'Natural Language Processing, Generative AI',
    email: 'vignesh@rit.edu',
    qualification: 'B.E. (CSE), M.E. (Artificial Intelligence), Ph.D. (Natural Language Processing)',
    experience: '6 Years',
    subjectsHandling: 'Natural Language Processing, Generative AI, Machine Learning, Data Science',
    researchAreas: 'Large Language Models, Conversational AI, Explainable AI',
    officeHours: 'Mon–Fri, 2:00 PM–4:00 PM',
    phone: '+91 98765 43226',
  }
];

// ─── Events ──────────────────────────────────────────────────────────────────
export const EVENTS_DATA: Event[] = [
  {
    id: '1',
    title: 'Fresher\'s Orientation Day 2025',
    description: 'Welcome ceremony for the new batch of students. Meet faculty, seniors, and explore campus.',
    date: '2025-08-05',
    time: '09:00 AM',
    venue: 'Main Auditorium',
    organizer: 'Student Council',
    category: 'seminar',
    isUpcoming: true,
  },
  {
    id: '2',
    title: 'Hackathon 2025 – RIT Code Fest',
    description: 'A 24-hour hackathon open to all departments. Build innovative solutions for real-world problems.',
    date: '2025-08-20',
    time: '08:00 AM',
    venue: 'Computer Lab Complex',
    organizer: 'CSE Department',
    category: 'technical',
    isUpcoming: true,
  },
  {
    id: '3',
    title: 'Techno Cultural Fest – RITMO',
    description: 'Annual cultural and technical fest with competitions, performances, and prize money up to ₹2 lakhs.',
    date: '2025-09-15',
    time: '10:00 AM',
    venue: 'College Ground',
    organizer: 'Arts & Cultural Committee',
    category: 'cultural',
    isUpcoming: true,
  },
  {
    id: '4',
    title: 'Industry Expert Talk – AI & Future',
    description: 'Guest lecture by industry experts from Google and Microsoft on AI trends and career opportunities.',
    date: '2025-08-10',
    time: '02:00 PM',
    venue: 'Seminar Hall',
    organizer: 'ECE Department',
    category: 'seminar',
    isUpcoming: true,
  },
];

// ─── Clubs ───────────────────────────────────────────────────────────────────
export const CLUBS_DATA: Club[] = [
  {
    id: 'stellar_space_tech',
    name: 'STELLAR SPACE TECH CLUB',
    description: 'Space technology, astronomy, satellite systems, and space science exploration at RIT.',
    details: 'RIT Stellar Space Tech Club brings together space enthusiasts, students, and aspiring aerospace engineers to explore astronomy, satellite communication, rocketry, and cutting-edge space technology through workshops, observational sessions, and technical projects.',
    category: 'Technical',
    members: 94,
    presidentName: 'Student Space Lead',
    year: 'Senior Year',
    contactEmail: 'spacetech@ritchennai.edu.in',
    contactPhone: '+91 98765 43210',
    icon: 'Rocket',
    logoUrl: '/clubs/stellar_space_tech.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/stellarspacetechclub/',
    },
  },
  {
    id: 'podx',
    name: 'podX-RIT (PODCAST CLUB)',
    description: 'Real talks. Raw feels. Because every story deserves to be heard. Official Podcast Club of RIT.',
    details: 'podX-RIT is the official Podcast and Radio Club of Rajalakshmi Institute of Technology. Bringing student stories, Switcheroo interviews, RJ sessions, and inspiring student & faculty conversations to life.',
    category: 'Creative',
    members: 1097,
    presidentName: 'Lead RJ / Podcaster',
    year: 'Senior Year',
    contactEmail: 'podx@ritchennai.edu.in',
    contactPhone: '+91 98765 43211',
    icon: 'Mic',
    logoUrl: '/clubs/podx.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/podxrit/',
      website: 'https://linktr.ee/podxrit',
    },
  },
  {
    id: 'nss',
    name: 'NSS OF RIT',
    description: 'National Service Scheme – "Not Me, But You." Official Social Service Club of RIT.',
    details: 'NSS of Rajalakshmi Institute of Technology engages students in community service, social awareness drives, blood donation camps, road safety campaigns, and nation-building initiatives.',
    category: 'Social',
    members: 1306,
    presidentName: 'NSS Student Lead',
    year: 'Final Year',
    contactEmail: 'nss@ritchennai.edu.in',
    contactPhone: '+91 98765 43212',
    icon: 'HeartHandshake',
    logoUrl: '/clubs/nss.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/nss.rit/',
    },
  },
  {
    id: 'artist_league',
    name: 'ARTIST LEAGUE (CULTURAL CELL)',
    description: 'Official Cultural Cell of RIT covering Dance (R-Square), Band (Euphoria), Rap & Classical.',
    details: 'Artist League is the umbrella cultural organization of RIT incorporating R-Square (Dance), Euphoria (Band), Raptology (Rap), and Classic Beat (Classical). It organizes cultural fests, talent shows, and 60 Seconds to Fame competitions.',
    category: 'Creative',
    members: 1093,
    presidentName: 'Cultural Secretary',
    year: 'Final Year',
    contactEmail: 'artistleague@ritchennai.edu.in',
    contactPhone: '+91 98765 43213',
    icon: 'Sparkles',
    logoUrl: '/clubs/artist_league.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/artist_league_rit/',
    },
  },
  {
    id: 'infinitus',
    name: 'INFINITUS CLUB (MATHS CLUB)',
    description: 'Where Logic Meets Innovation. Mathematics workshops, PiDoku, GraphQuest & tech competitions.',
    details: 'Infinitus Club is the official Mathematics & Aptitude Club of RIT, hosting Pi-Quest, PiDoku Decode π, GraphQuest, logic puzzles, speed calculations, and analytical problem-solving workshops.',
    category: 'Technical',
    members: 557,
    presidentName: 'Mathematics Lead',
    year: 'Third Year',
    contactEmail: 'infinitus@ritchennai.edu.in',
    contactPhone: '+91 98765 43214',
    icon: 'Calculator',
    logoUrl: '/clubs/infinitus.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/infinitus_club.rit/',
      whatsapp: 'https://chat.whatsapp.com/LeCKYtgzdzJ5E6sL0WjYIHf',
    },
  },
  {
    id: 'vaarithi',
    name: 'VAARITHI TAMIL CLUB',
    description: 'இராசலட்சுமி தொழில்நுட்பக் கல்லூரியின் மாணவர் தமிழ் மன்றம் (RIT Tamil Mandram).',
    details: 'Vaarithi Muthamizh Mandram of RIT celebrates Tamil literature, poetry, debate (Tamizhsudar), Tamil New Year celebrations, and preserving rich Tamil culture and heritage.',
    category: 'Creative',
    members: 848,
    presidentName: 'Tamil Mandram Lead',
    year: 'Final Year',
    contactEmail: 'vaarithi@ritchennai.edu.in',
    contactPhone: '+91 98765 43215',
    icon: 'BookOpen',
    logoUrl: '/clubs/vaarithi.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/vaarithi_rit/',
    },
  },
  {
    id: 'fusion',
    name: 'FUSION CLUB (ENGLISH & LITERATURE)',
    description: 'A platform to delve into the beauty of language, literature, essays, and power of words.',
    details: 'Fusion Club of RIT is the English Literary Club organizing essay writing contests, Lips Don’t Lie games, Fusion Treasure Hunt, debates, and creative writing workshops.',
    category: 'Creative',
    members: 815,
    presidentName: 'Literary President',
    year: 'Third Year',
    contactEmail: 'fusionclub@ritchennai.edu.in',
    contactPhone: '+91 98765 43216',
    icon: 'Languages',
    logoUrl: '/clubs/fusion.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/fusionclub_rit/',
    },
  },
  {
    id: 'nippon',
    name: 'NIPPON CLUB (JAPANESE CULTURE)',
    description: 'Celebrating Japanese culture, language, anime, movie review nights & vibrant community.',
    details: 'Nippon Club of RIT brings Japanese language learning, Kizuna Canvas relay drawing, Koe Nashi voice challenge, anime screenings, and Japanese cultural immersion to RIT students.',
    category: 'Creative',
    members: 649,
    presidentName: 'Nippon President',
    year: 'Third Year',
    contactEmail: 'nippon@ritchennai.edu.in',
    contactPhone: '+91 98765 43217',
    icon: 'Globe',
    logoUrl: '/clubs/nippon.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/nippon_rit/',
    },
  },
  {
    id: 'unnat_bharat',
    name: 'RIT UNNAT BHARAT ABHIYAN (UBA)',
    description: 'Unite, socialize, thrive together! Official Social Impact & Rural Development Club.',
    details: 'RIT Unnat Bharat Abhiyan (UBA) club focuses on sustainable village development, plantation drives, environmental awareness, and impactful social initiatives across rural Tamil Nadu.',
    category: 'Social',
    members: 1153,
    presidentName: 'UBA Core Lead',
    year: 'Final Year',
    contactEmail: 'uba@ritchennai.edu.in',
    contactPhone: '+91 98765 43218',
    icon: 'Users',
    logoUrl: '/clubs/unnat_bharat.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/ritunnatbharatabhiyan/',
    },
  },
  {
    id: 'mediastic',
    name: 'MEDIASTIC HUB (SOCIAL MEDIA CLUB)',
    description: 'Official Social Media & Digital Content Creation Club of Rajalakshmi Institute of Technology.',
    details: 'Mediastic Hub handles official video production, campus media coverage, event highlights for RobochipX & Quant-a-thon, photography exhibitions, and RIT digital channels.',
    category: 'Creative',
    members: 1351,
    presidentName: 'Media Hub Lead',
    year: 'Final Year',
    contactEmail: 'mediastichub@ritchennai.edu.in',
    contactPhone: '+91 98765 43219',
    icon: 'Camera',
    logoUrl: '/clubs/mediastic.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/mediastichub_rit/',
      youtube: 'https://www.youtube.com/@rajalakshmiinstituteoftech444',
    },
  },
  {
    id: 'helios',
    name: 'HELIOS RIT (PHOTOGRAPHY CLUB)',
    description: 'Capturing Life\'s Moments, One Frame at a Time. Showcasing cinematic shots & campus stories.',
    details: 'Helios RIT Official is the premier photography and filmmaking club of RIT, capturing campus events, hosting photography contests, guest lectures, and showcasing cinematic stories of RIT.',
    category: 'Creative',
    members: 2455,
    presidentName: 'Photography Lead',
    year: 'Final Year',
    contactEmail: 'helios@ritchennai.edu.in',
    contactPhone: '+91 98765 43220',
    icon: 'Camera',
    logoUrl: '/clubs/helios.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/helios.rit/',
    },
  },
  {
    id: 'techspark',
    name: 'TECHSPARK CLUB RIT',
    description: 'Where Tech meets creativity, Sparks fly! Fostering innovation in every byte.',
    details: 'TechSpark Club RIT is the technical innovation club driving Web3 Camp Meets AI, GirlScript hackathons, Spark Booths, coding competitions, and hands-on developer projects.',
    category: 'Technical',
    members: 672,
    presidentName: 'TechSpark Lead',
    year: 'Third Year',
    contactEmail: 'techspark@ritchennai.edu.in',
    contactPhone: '+91 98765 43221',
    icon: 'Zap',
    logoUrl: '/clubs/techspark.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/techspark.rit/',
      whatsapp: 'https://chat.whatsapp.com/I8B5Wdybrew2dYYDrE4PG',
    },
  },
  {
    id: 'wec',
    name: 'WOMEN EMPOWERMENT CELL (WEC)',
    description: 'Empower • Excel • Elevate. Supporting women in technology, leadership & coding.',
    details: 'Women Empowerment Cell (WEC RIT) organizes She Shines @ Hexaware coding challenges, Women’s Empowerment Week, ZYRA Days, leadership seminars, and career development initiatives.',
    category: 'Social',
    members: 428,
    presidentName: 'Pooja WYA',
    year: 'Final Year',
    contactEmail: 'wec@ritchennai.edu.in',
    contactPhone: '+91 98765 43222',
    icon: 'Sparkles',
    logoUrl: '/clubs/wec.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/wec.rit/',
    },
  },
  {
    id: 'rotaract',
    name: 'ROTARACT CLUB OF RIT (RCRIT)',
    description: 'Embrace the joy of giving. Official Rotaract organization for leadership & service.',
    details: 'Rotaract Club of RIT (RCRIT) under Rotary International sponsors Bloom mental health seminars, Phoenix fests, RITARIQ 365, Ryla leadership camps, and community blood donation drives.',
    category: 'Social',
    members: 1813,
    presidentName: 'Hari Balaji',
    year: 'Final Year',
    contactEmail: 'rotaract@ritchennai.edu.in',
    contactPhone: '+91 98765 43223',
    icon: 'HeartHandshake',
    logoUrl: '/clubs/rotaract.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/rcrit/',
    },
  },
  {
    id: 'yuva',
    name: 'Yi-CH YUVA RIT',
    description: 'Official Page of YUVA Club RIT under Young Indians (Yi). Inspiring youth leadership.',
    details: 'Yi-CH YUVA RIT leads Chennai Get Talent, Safe Miles road safety awareness, Blogathons, Tree Plantation drives (500 Trees Mission), and youth leadership conventions.',
    category: 'Social',
    members: 1460,
    presidentName: 'YUVA Student Chair',
    year: 'Final Year',
    contactEmail: 'yuva@ritchennai.edu.in',
    contactPhone: '+91 98765 43224',
    icon: 'Rocket',
    logoUrl: '/clubs/yuva.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/yuva_rit/',
    },
  },
  {
    id: 'wistem',
    name: 'WiSTEM CLUB OF RIT',
    description: 'Women in STEM Club. AI Quests, STEM Chronicles, CodeVsClick & maker empowering events.',
    details: 'WiSTEM Club of RIT empowers women in Science, Technology, Engineering, and Mathematics through AI Quests, STEM Chronicles newsletter, CodeVsClick contests, and technical workshops.',
    category: 'Technical',
    members: 453,
    presidentName: 'WiSTEM Lead',
    year: 'Third Year',
    contactEmail: 'wistem@ritchennai.edu.in',
    contactPhone: '+91 98765 43225',
    icon: 'Atom',
    logoUrl: '/clubs/wistem.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/wistem._.rit/',
      website: 'https://www.rityatra.in/',
    },
  },
  {
    id: 'steam',
    name: 'STEAM CLUB RIT',
    description: 'Innovate - Collaborate - Elevate. Hands-on RobochipX, Quant-a-thon & AI/Chip design.',
    details: 'STEAM Club RIT focuses on hands-on project creation, RobochipX 24-hour hackathons, Quant-a-thon quantum technology events, chip design, and robotics innovations.',
    category: 'Technical',
    members: 895,
    presidentName: 'STEAM President',
    year: 'Final Year',
    contactEmail: 'steamclub@ritchennai.edu.in',
    contactPhone: '+91 98765 43226',
    icon: 'Printer',
    logoUrl: '/clubs/steam.png',
    socialLinks: {
      instagram: 'https://www.instagram.com/steam_club.rit/',
    },
  },
];

// ─── Community Q&A ───────────────────────────────────────────────────────────
export const QUESTIONS_DATA: Question[] = [
  {
    id: '1',
    title: 'How is the hostel facility at RIT?',
    body: 'I\'m a fresher joining CSE. Can someone give me honest reviews about the hostel rooms, food, and wifi?',
    author: 'Priya S.',
    createdAt: '2025-07-15T10:00:00Z',
    answers: 12,
    votes: 45,
    tags: ['hostel', 'accommodation', 'fresher'],
    isAnswered: true,
  },
  {
    id: '2',
    title: 'Which subjects are most important in 1st semester CSE?',
    body: 'I want to prepare in advance. What are the toughest subjects in the first semester?',
    author: 'Ravi K.',
    createdAt: '2025-07-18T14:30:00Z',
    answers: 8,
    votes: 38,
    tags: ['academics', 'cse', 'semester-1'],
    isAnswered: true,
  },
  {
    id: '3',
    title: 'Is there a gym on campus?',
    body: 'Does RIT have a gym or fitness center for students? What are the timings?',
    author: 'Arun M.',
    createdAt: '2025-07-20T09:15:00Z',
    answers: 4,
    votes: 22,
    tags: ['campus', 'sports', 'facilities'],
    isAnswered: false,
  },
];

// ─── Confessions ─────────────────────────────────────────────────────────────
export const CONFESSIONS_DATA: Confession[] = [
  {
    id: '1',
    content: 'I was so nervous on my first day that I went to the wrong department. A senior helped me out and became my best friend. RIT has such a warm community! 🧡',
    createdAt: '2025-07-19T11:00:00Z',
    reactions: 87,
    category: 'Wholesome',
  },
  {
    id: '2',
    content: 'The library WiFi is actually faster than my home connection. No complaints from me 😂',
    createdAt: '2025-07-18T15:30:00Z',
    reactions: 134,
    category: 'Funny',
  },
  {
    id: '3',
    content: 'I have a crush on someone in my class but I\'m too shy to talk. We have been in the same group project for 2 months now 😅',
    createdAt: '2025-07-17T09:00:00Z',
    reactions: 212,
    category: 'Crush',
  },
];

// ─── Toolkit Items ───────────────────────────────────────────────────────────
export const TOOLKIT_ITEMS: ToolkitItem[] = [
  { id: '1', title: 'Timetable 2025-26', description: 'Semester timetable for all departments', type: 'pdf', url: '#', icon: 'Clock', category: 'Academic' },
  { id: '2', title: 'Academic Calendar', description: 'Important dates, holidays, and exams', type: 'pdf', url: '#', icon: 'CalendarDays', category: 'Academic' },
  { id: '3', title: 'Fee Payment Form', description: 'Semester fee payment form', type: 'form', url: '#', icon: 'CreditCard', category: 'Administrative' },
  { id: '4', title: 'Syllabus 2025', description: 'Updated syllabus for all semesters', type: 'pdf', url: '#', icon: 'BookMarked', category: 'Academic' },
  { id: '5', title: 'Regulations 2021', description: 'Anna University regulations document', type: 'pdf', url: '#', icon: 'ScrollText', category: 'Regulatory' },
  { id: '6', title: 'ERP Portal Guide', description: 'Step-by-step guide to use ERP system', type: 'pdf', url: '#', icon: 'Monitor', category: 'Guide' },
  { id: '7', title: 'Leave Application', description: 'Student leave application form', type: 'form', url: '#', icon: 'FileCheck', category: 'Administrative' },
  { id: '8', title: 'Bus Pass Form', description: 'Apply for monthly bus pass', type: 'form', url: '#', icon: 'Bus', category: 'Administrative' },
];

// ─── Campus Locations ────────────────────────────────────────────────────────
export const CAMPUS_LOCATIONS: CampusLocation[] = [
  { id: 'dept', name: 'Departments', icon: 'Building2' },
  { id: 'library', name: 'Library', icon: 'Library' },
  { id: 'labs', name: 'Labs', icon: 'FlaskConical' },
  { id: 'hostel', name: 'Hostels', icon: 'Home' },
  { id: 'canteen', name: 'Canteen', icon: 'UtensilsCrossed' },
  { id: 'busstop', name: 'Bus Stop', icon: 'Bus' },
  { id: 'auditorium', name: 'Auditorium', icon: 'Theater' },
  { id: 'sports', name: 'Sports Ground', icon: 'Trophy' },
];

// ─── AI Suggested Prompts ────────────────────────────────────────────────────
export const AI_SUGGESTED_PROMPTS = [
  'What documents do I need for admission?',
  'How do I access the ERP portal?',
  'Tell me about hostel facilities',
  'What are the top clubs at RIT?',
  'How does the bus route system work?',
  'What are the library timings?',
  'Who is the HOD of CSE department?',
  'What is the dress code at RIT?',
];

// ─── Departments ─────────────────────────────────────────────────────────────
export const DEPARTMENTS = [
  'All Departments',
  'Computer Science & Engineering',
  'Computer Science & Business Systems',
  'Artificial Intelligence & Machine Learning',
  'Electronics & Communication Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Artificial Intelligence & Data Science',
  'Electrical & Electronics Engineering',
];
